export const testUsers = [
  {
    id: 1,
    username: "SUP-001",
    email: "superadmin@company.com",
    password: "Super@123",
    role: "superadmin",
    isTwoFactor: true,
    isForgotPassword: true,
    profile: {
      fullName: "Super Admin",
      department: "Management",
      phone: "+91 9876543210",
      status: "active",
      createdAt: "2024-01-10",
    },
  },
  {
    id: 2,
    username: "ADM-001",
    email: "admin@company.com",
    password: "Admin@123",
    role: "admin",
    isTwoFactor: true,
    isForgotPassword: true,
    profile: {
      fullName: "System Admin",
      department: "IT",
      phone: "+91 9876500000",
      status: "active",
      createdAt: "2024-02-15",
    },
  },
  {
    id: 3,
    username: "USR-001",
    email: "user@company.com",
    password: "User@123",
    role: "user",
    isTwoFactor: false,
    isForgotPassword: false,
    profile: {
      fullName: "Regular User",
      department: "Sales",
      phone: "+91 9000000001",
      status: "active",
      createdAt: "2024-03-01",
    },
  },
  {
    id: 4,
    username: "SUPV-001",
    email: "supervisor@company.com",
    password: "Supervisor@123",
    role: "supervisor",
    isTwoFactor: false,
    isForgotPassword: false,
    profile: {
      fullName: "Team Supervisor",
      department: "Operations",
      phone: "+91 9000000002",
      status: "active",
      createdAt: "2024-03-20",
    },
  },
];
